### ISSUE TITLE
provide the json,sometimes overview01.png can not load into comfyui lol

### ISSUE THREAD

**Issue by 1zhangyy1** [mirabarukaso/ComfyUI_Mira#2]
It's very nice work! Could you  provide the json as well.sometimes overview01.png can not load into comfyui lol

**Comment by mirabarukaso** [comment]
oops! that's my fault, it's a normal screenshot. Just updated to my latest workflow shot, try loading `overview01.png` again, it should work now.
In case I screwed it up again, I'll upload the same workflow json here.

Cheers

[workflow.component.json](https://github.com/mirabarukaso/ComfyUI_Mira/files/15110410/workflow.component.json)
