### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by nakoland** [mirabarukaso/ComfyUI_Mira#4]
https://github.com/mirabarukaso/ComfyUI_Mira/blob/2c75ff5a61eb0f13e1f9d0ac692e19a31e96d0b6/Logic.py#L230

def EvenOrOddEx(self, num,):       
     return (CheckEvenOrOdd(num),)

Thank you for making a good node. There's a bug in this part. It worked as I fixed it down.

def EvenOrOddEx(self, num,):       
     return CheckEvenOrOdd(num)

**Comment by mirabarukaso** [comment]
Confirmed, thanks for your feedback. My workflow now switches to `Even or Odd List`, that should be something I forget to change.
